name: '[CI] On Pull Request to master'

on:
  pull_request:
    branches:
      - master

jobs:
  inspection_and_tests_pull_request_master:
    name: Inspection and Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['10', '12']
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: npm install
      - name: Run format check with prettier
        run: npm run format:check
      - name: Run lint check
        run: npm run lint:check
      - name: Run unit tests
        run: npm run test:CI
        continue-on-error: true
      - name: Run build on ngx-graphs-d3 to check that it succeeds
        run: npm run build:prod:lib
      - name: Run build on ngx-graphs-d3-doc to check that it succeeds
        run: npm run build:prod:doc
